apiVersion: v1
kind: Pod
metadata:
  name: memory-leak-pod
spec:
  containers:
  - name: leaker
    image: alpine
    command: ["sh", "-c", "tail -f /dev/null"]
    resources:
      limits:
        memory: "20Mi"
  restartPolicy: Never